### ISSUE TITLE
Propose an initial server stub based on swagger output

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api-app#10]
The server stub will be automatically  generated from swagger file so to be updated when swagger file is.

The implementation is java.

**Comment by tloubrieu-jpl** [comment]
A library is generated from : https://github.com/NASA-PDS/pds-api-core
An dummy java implementation is generated in repo: https://github.com/NASA-PDS/pds-api-service

**Comment by jordanpadams** [comment]
@tloubrieu-jpl do we want to potentially add `java` into the repo name so we can potentially have a `python`, `npm`, etc.?
